import type { ContentItem } from "@/games/types/game.types";

// Full sentences make the subject and time explicit in every practice language.
// Past forms use the natural completed-past construction of each language.
type Sentence = [
  es: string,
  ca: string,
  en: string,
  fr: string,
  de: string,
  it: string,
];
const sentences: Record<"present" | "past" | "future", Sentence[]> = {
  present: [
    [
      "Yo trabajo cada día",
      "Jo treballo cada dia",
      "I work every day",
      "Je travaille chaque jour",
      "Ich arbeite jeden Tag",
      "Io lavoro ogni giorno",
    ],
    [
      "Tú estudias cada día",
      "Tu estudies cada dia",
      "You study every day",
      "Tu étudies chaque jour",
      "Du lernst jeden Tag",
      "Tu studi ogni giorno",
    ],
    [
      "Ella canta cada día",
      "Ella canta cada dia",
      "She sings every day",
      "Elle chante chaque jour",
      "Sie singt jeden Tag",
      "Lei canta ogni giorno",
    ],
    [
      "Él cocina cada día",
      "Ell cuina cada dia",
      "He cooks every day",
      "Il cuisine chaque jour",
      "Er kocht jeden Tag",
      "Lui cucina ogni giorno",
    ],
    [
      "Yo leo cada día",
      "Jo llegeixo cada dia",
      "I read every day",
      "Je lis chaque jour",
      "Ich lese jeden Tag",
      "Io leggo ogni giorno",
    ],
    [
      "Tú escribes cada día",
      "Tu escrius cada dia",
      "You write every day",
      "Tu écris chaque jour",
      "Du schreibst jeden Tag",
      "Tu scrivi ogni giorno",
    ],
    [
      "Ella nada cada día",
      "Ella neda cada dia",
      "She swims every day",
      "Elle nage chaque jour",
      "Sie schwimmt jeden Tag",
      "Lei nuota ogni giorno",
    ],
    [
      "Él baila cada día",
      "Ell balla cada dia",
      "He dances every day",
      "Il danse chaque jour",
      "Er tanzt jeden Tag",
      "Lui balla ogni giorno",
    ],
  ],
  past: [
    [
      "Yo trabajé ayer",
      "Jo vaig treballar ahir",
      "I worked yesterday",
      "J'ai travaillé hier",
      "Ich habe gestern gearbeitet",
      "Io ho lavorato ieri",
    ],
    [
      "Tú estudiaste ayer",
      "Tu vas estudiar ahir",
      "You studied yesterday",
      "Tu as étudié hier",
      "Du hast gestern gelernt",
      "Tu hai studiato ieri",
    ],
    [
      "Ella cantó ayer",
      "Ella va cantar ahir",
      "She sang yesterday",
      "Elle a chanté hier",
      "Sie hat gestern gesungen",
      "Lei ha cantato ieri",
    ],
    [
      "Él cocinó ayer",
      "Ell va cuinar ahir",
      "He cooked yesterday",
      "Il a cuisiné hier",
      "Er hat gestern gekocht",
      "Lui ha cucinato ieri",
    ],
    [
      "Yo leí ayer",
      "Jo vaig llegir ahir",
      "I read yesterday",
      "J'ai lu hier",
      "Ich habe gestern gelesen",
      "Io ho letto ieri",
    ],
    [
      "Tú escribiste ayer",
      "Tu vas escriure ahir",
      "You wrote yesterday",
      "Tu as écrit hier",
      "Du hast gestern geschrieben",
      "Tu hai scritto ieri",
    ],
    [
      "Ella nadó ayer",
      "Ella va nedar ahir",
      "She swam yesterday",
      "Elle a nagé hier",
      "Sie ist gestern geschwommen",
      "Lei ha nuotato ieri",
    ],
    [
      "Él bailó ayer",
      "Ell va ballar ahir",
      "He danced yesterday",
      "Il a dansé hier",
      "Er hat gestern getanzt",
      "Lui ha ballato ieri",
    ],
  ],
  future: [
    [
      "Yo trabajaré mañana",
      "Jo treballaré demà",
      "I will work tomorrow",
      "Je travaillerai demain",
      "Ich werde morgen arbeiten",
      "Io lavorerò domani",
    ],
    [
      "Tú estudiarás mañana",
      "Tu estudiaràs demà",
      "You will study tomorrow",
      "Tu étudieras demain",
      "Du wirst morgen lernen",
      "Tu studierai domani",
    ],
    [
      "Ella cantará mañana",
      "Ella cantarà demà",
      "She will sing tomorrow",
      "Elle chantera demain",
      "Sie wird morgen singen",
      "Lei canterà domani",
    ],
    [
      "Él cocinará mañana",
      "Ell cuinarà demà",
      "He will cook tomorrow",
      "Il cuisinera demain",
      "Er wird morgen kochen",
      "Lui cucinerà domani",
    ],
    [
      "Yo leeré mañana",
      "Jo llegiré demà",
      "I will read tomorrow",
      "Je lirai demain",
      "Ich werde morgen lesen",
      "Io leggerò domani",
    ],
    [
      "Tú escribirás mañana",
      "Tu escriuràs demà",
      "You will write tomorrow",
      "Tu écriras demain",
      "Du wirst morgen schreiben",
      "Tu scriverai domani",
    ],
    [
      "Ella nadará mañana",
      "Ella nedarà demà",
      "She will swim tomorrow",
      "Elle nagera demain",
      "Sie wird morgen schwimmen",
      "Lei nuoterà domani",
    ],
    [
      "Él bailará mañana",
      "Ell ballarà demà",
      "He will dance tomorrow",
      "Il dansera demain",
      "Er wird morgen tanzen",
      "Lui ballerà domani",
    ],
  ],
};

export function tenseItems(tense: keyof typeof sentences): ContentItem[] {
  return sentences[tense].map(([es, ca, en, fr, de, it], index) => ({
    id: `${tense}-${index + 1}`,
    words: {
      es: [es, es.replace(/^(Yo|Tú|Ella|Él) /, "")],
      ca: [ca, ca.replace(/^(Jo|Tu|Ella|Ell) /, "")],
      en: [
        en,
        ...(tense === "future"
          ? [en.replace(/^(I|You|She|He) will /, "$1'll ")]
          : []),
      ],
      fr: [fr],
      de: [de],
      it: [it, it.replace(/^(Io|Tu|Lei|Lui) /, "")],
    },
  }));
}
