import type { Locale } from "@/i18n/messages";
export const learnCopy = {
  es: {
    nav: "topics",
    kicker: "PEQUEÑOS PASOS, GRANDES PARTIDAS",
    title: "Aprende. Descubre. ¡Juega!",
    intro:
      "Todo lo que necesitas para los juegos, a tu ritmo. Explora una ficha, pon a prueba tu memoria y lleva lo aprendido a la partida.",
    language: "Quiero aprender",
    source: "Con traducciones en",
    route: "Tu ruta de aprendizaje",
    cards: "fichas",
    mastered: "dominadas",
    saved: "Tu progreso se guarda en este navegador, por tema e idiomas.",
    storage:
      "No se puede guardar el progreso. Puedes seguir aprendiendo en esta sesión.",
    discover: "1. Descubre",
    challenge: "2. Ponte a prueba",
    library: "3. Consulta todas las fichas",
    reveal: "Descubrir respuesta",
    hide: "Ocultar respuesta",
    previous: "← Anterior",
    next: "Siguiente →",
    question: "¿Cuál es la traducción?",
    correct: "¡Lo tienes! Una ficha más dominada.",
    wrong: "Casi… Mira la respuesta y vuelve a intentarlo más adelante.",
    answer: "Respuesta",
    play: "¡A jugar!",
    search: "Buscar una palabra o un número",
    empty: "No hay fichas con esa búsqueda.",
    complete: "¡Has dominado todas las fichas de este tema!",
    review: "Volver a repasar",
    start: "Empezar reto",
    hint: "Piensa la respuesta antes de descubrirla. Después, comprueba lo que recuerdas en el reto.",
    tips: [
      "Empieza por el 1–20 y las decenas. Después combina decenas y unidades. Recorre todas las fichas hasta el 99: en el bingo reconocerás la palabra y marcarás su cifra.",
      "Asocia cada dibujo con su palabra. Lee también las variantes: en los juegos de escritura se acepta cualquiera de las que aparecen en la ficha. Después practica sin mirar la imagen.",
      "El pronombre indica quién realiza la acción. Fíjate en la persona, el número y el trato formal. Una misma palabra puede tener varios significados: el contexto de cada ficha te ayudará.",
      "Aprende las frases por familias: estar feliz, beber agua, comer pan y vivir aquí. Compara cómo cambia el verbo con yo, tú, él y ella. Memoriza la frase completa, incluidos artículos y apóstrofos.",
    ],
    spelling:
      "Consejo: respeta los acentos y la escritura. Las variantes separadas por / también son respuestas válidas.",
  },
  ca: {
    nav: "Temari",
    kicker: "PETITS PASSOS, GRANS PARTIDES",
    title: "Aprèn. Descobreix. Juga!",
    intro:
      "Tot el que necessites per als jocs, al teu ritme. Explora una fitxa, posa a prova la memòria i porta el que has après a la partida.",
    language: "Vull aprendre",
    source: "Amb traduccions en",
    route: "La teva ruta d’aprenentatge",
    cards: "fitxes",
    mastered: "dominades",
    saved: "El progrés es desa en aquest navegador, per tema i idiomes.",
    storage:
      "No es pot desar el progrés. Pots continuar aprenent en aquesta sessió.",
    discover: "1. Descobreix",
    challenge: "2. Posa’t a prova",
    library: "3. Consulta totes les fitxes",
    reveal: "Descobrir resposta",
    hide: "Amagar resposta",
    previous: "← Anterior",
    next: "Següent →",
    question: "Quina és la traducció?",
    correct: "Ho tens! Una fitxa més dominada.",
    wrong: "Gairebé… Mira la resposta i torna-ho a provar més endavant.",
    answer: "Resposta",
    play: "A jugar!",
    search: "Cerca una paraula o un nombre",
    empty: "No hi ha fitxes amb aquesta cerca.",
    complete: "Has dominat totes les fitxes d’aquest tema!",
    review: "Tornar a repassar",
    start: "Començar repte",
    hint: "Pensa la resposta abans de descobrir-la. Després comprova què recordes al repte.",
    tips: [
      "Comença per l’1–20 i les desenes. Després combina desenes i unitats. Recorre les fitxes fins al 99: al bingo reconeixeràs la paraula i marcaràs la xifra.",
      "Associa cada dibuix amb la paraula. Llegeix també les variants: als jocs d’escriptura s’accepta qualsevol de les que apareixen a la fitxa. Després practica sense mirar la imatge.",
      "El pronom indica qui fa l’acció. Fixa’t en la persona, el nombre i el tractament formal. Una mateixa paraula pot tenir diversos significats: el context de cada fitxa t’ajudarà.",
      "Aprèn les frases per famílies: estar feliç, beure aigua, menjar pa i viure aquí. Compara com canvia el verb amb jo, tu, ell i ella. Memoritza la frase sencera, inclosos articles i apòstrofs.",
    ],
    spelling:
      "Consell: respecta els accents i l’escriptura. Les variants separades per / també són respostes vàlides.",
  },
  en: {
    nav: "Learn",
    kicker: "SMALL STEPS, GREAT GAMES",
    title: "Learn. Discover. Play!",
    intro:
      "Everything you need for the games, at your own pace. Explore a card, test your memory and take your new skills into a game.",
    language: "I want to learn",
    source: "With translations in",
    route: "Your learning path",
    cards: "cards",
    mastered: "mastered",
    saved:
      "Progress is saved in this browser for each topic and language pair.",
    storage: "Progress cannot be saved. You can keep learning in this session.",
    discover: "1. Discover",
    challenge: "2. Test yourself",
    library: "3. Browse all cards",
    reveal: "Reveal answer",
    hide: "Hide answer",
    previous: "← Previous",
    next: "Next →",
    question: "Which translation is correct?",
    correct: "You’ve got it! One more card mastered.",
    wrong: "Almost… Check the answer and try again later.",
    answer: "Answer",
    play: "Let’s play!",
    search: "Search for a word or number",
    empty: "No cards match your search.",
    complete: "You’ve mastered every card in this topic!",
    review: "Review again",
    start: "Start challenge",
    hint: "Think of the answer before revealing it. Then test what you remember in the challenge.",
    tips: [
      "Start with 1–20 and the tens. Then combine tens and units. Explore every card up to 99: in bingo you’ll recognise the word and mark its numeral.",
      "Connect each picture with its word. Read the alternatives too: writing games accept any variant shown on the card. Then practise without looking at the picture.",
      "Subject pronouns tell you who performs an action. Notice person, number and formal address. One word can have several meanings: each card’s context will help you.",
      "Learn sentences in families: being happy, drinking water, eating bread and living here. Compare how verbs change with I, you, he and she. Remember the whole sentence, including articles and apostrophes.",
    ],
    spelling:
      "Tip: pay attention to accents and spelling. Variants separated by / are also accepted answers.",
  },
} satisfies Record<Locale, unknown>;
