export const clothes = [
  [
    "t-shirt",
    "👕",
    "camiseta",
    "samarreta",
    "T-shirt/t shirt/tshirt",
    "T-shirt/tee-shirt",
    "T-Shirt",
    "maglietta/T-shirt",
  ],
  [
    "jeans",
    "👖",
    "vaqueros/pantalones vaqueros/tejanos",
    "texans/pantalons texans",
    "jeans",
    "jean/jeans",
    "Jeans",
    "jeans",
  ],
  [
    "dress",
    "👗",
    "vestido",
    "vestit",
    "dress",
    "robe",
    "Kleid",
    "vestito/abito",
  ],
  ["coat", "🧥", "abrigo", "abric", "coat", "manteau", "Mantel", "cappotto"],
  [
    "socks",
    "🧦",
    "calcetines",
    "mitjons",
    "socks",
    "chaussettes",
    "Socken/Strümpfe",
    "calzini/calze",
  ],
  ["shoe", "👞", "zapato", "sabata", "shoe", "chaussure", "Schuh", "scarpa"],
  [
    "hat",
    "🎩",
    "sombrero/sombrero de copa",
    "barret/barret de copa",
    "hat/top hat",
    "chapeau/chapeau haut-de-forme",
    "Hut/Zylinder",
    "cappello/cilindro",
  ],
  ["scarf", "🧣", "bufanda", "bufanda", "scarf", "écharpe", "Schal", "sciarpa"],
] as const;
