export const food = [
  ["apple", "🍎", "manzana", "poma", "apple", "pomme", "Apfel", "mela"],
  [
    "banana",
    "🍌",
    "plátano/banana",
    "plàtan/banana",
    "banana",
    "banane",
    "Banane",
    "banana",
  ],
  ["bread", "🍞", "pan", "pa", "bread", "pain", "Brot", "pane"],
  [
    "cheese",
    "🧀",
    "queso",
    "formatge",
    "cheese",
    "fromage",
    "Käse",
    "formaggio",
  ],
  ["egg", "🥚", "huevo", "ou", "egg", "œuf/oeuf", "Ei", "uovo"],
  [
    "carrot",
    "🥕",
    "zanahoria",
    "pastanaga",
    "carrot",
    "carotte",
    "Karotte/Möhre",
    "carota",
  ],
  ["milk", "🥛", "leche", "llet", "milk", "lait", "Milch", "latte"],
  ["coffee", "☕", "café", "cafè", "coffee", "café", "Kaffee", "caffè"],
  [
    "strawberry",
    "🍓",
    "fresa",
    "maduixa",
    "strawberry",
    "fraise",
    "Erdbeere",
    "fragola",
  ],
  [
    "grapes",
    "🍇",
    "uvas",
    "raïm",
    "grapes",
    "raisin",
    "Trauben/Weintrauben",
    "uva",
  ],
] as const;
