export const home = [
  ["door", "🚪", "puerta", "porta", "door", "porte", "Tür", "porta"],
  ["bed", "🛏️", "cama", "llit", "bed", "lit", "Bett", "letto"],
  ["chair", "🪑", "silla", "cadira", "chair", "chaise", "Stuhl", "sedia"],
  [
    "sofa",
    "🛋️",
    "sofá",
    "sofà",
    "sofa/couch",
    "canapé/sofa",
    "Sofa/Couch",
    "divano",
  ],
  [
    "light-bulb",
    "💡",
    "bombilla",
    "bombeta",
    "light bulb/bulb",
    "ampoule",
    "Glühbirne",
    "lampadina",
  ],
  [
    "toilet",
    "🚽",
    "inodoro/váter/retrete",
    "vàter/inodor",
    "toilet",
    "toilettes/WC",
    "Toilette/Klo",
    "gabinetto/WC",
  ],
  [
    "bathtub",
    "🛁",
    "bañera",
    "banyera",
    "bath/bathtub",
    "baignoire",
    "Badewanne",
    "vasca da bagno/vasca",
  ],
  ["key", "🔑", "llave", "clau", "key", "clé/clef", "Schlüssel", "chiave"],
] as const;
