export const transport = [
  [
    "car",
    "🚗",
    "coche/auto/automóvil",
    "cotxe/automòbil",
    "car",
    "voiture/automobile",
    "Auto/Wagen",
    "auto/macchina/automobile",
  ],
  [
    "bus",
    "🚌",
    "autobús/bus",
    "autobús/bus",
    "bus",
    "bus/autobus",
    "Bus/Omnibus",
    "autobus/bus",
  ],
  ["train", "🚆", "tren", "tren", "train", "train", "Zug", "treno"],
  [
    "bicycle",
    "🚲",
    "bicicleta/bici",
    "bicicleta/bici",
    "bicycle/bike",
    "vélo/bicyclette",
    "Fahrrad/Rad",
    "bicicletta/bici",
  ],
  [
    "plane",
    "✈️",
    "avión",
    "avió",
    "plane/aeroplane/airplane",
    "avion",
    "Flugzeug",
    "aereo/aeroplano",
  ],
  [
    "sailboat",
    "⛵",
    "velero/barco de vela",
    "veler/vaixell de vela",
    "sailing boat/sailboat",
    "voilier/bateau à voile",
    "Segelboot",
    "barca a vela",
  ],
  ["taxi", "🚕", "taxi", "taxi", "taxi/cab", "taxi", "Taxi", "taxi/tassì"],
  [
    "motorbike",
    "🏍️",
    "moto/motocicleta",
    "moto/motocicleta",
    "motorbike/motorcycle",
    "moto/motocyclette",
    "Motorrad",
    "moto/motocicletta",
  ],
] as const;
